name: geo_cam_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

# Development-only dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
      - family: Kigali_Lx_Regular
        fonts:
          - asset: lib/assets/fonts/Kigali_Lx_Regular.otf 


  assets:
    - lib/assets/images/
    - lib/data/municipality/calkini/
    - lib/data/municipality/becal/
    - lib/data/municipality/dzitbalche/
    - lib/data/municipality/nunkini/
    - lib/assets/images/BC/
    - lib/assets/images/DiseñoHF.png
    - lib/assets/images/calkinibtn.png
    - lib/assets/images/becalbtn.jpg
    - lib/assets/images/dzitbalchebtn.jpeg
    - lib/assets/images/nunkinibtn.jpg
    - lib/assets/images/tutorial.png
    - lib/assets/images/artesania.jpg
    - lib/assets/images/tiendas.jpg
    - lib/assets/images/restaurante.jpg
    - lib/assets/images/hotel.jpeg
    - lib/assets/images/piscina.png
    - lib/assets/images/zonaarq.jpg
    - lib/assets/images/religion.jpg
    - lib/assets/images/cafeteria.jpg
    - lib/assets/images/transporte.png
    - lib/assets/images/lupa.png
    - lib/assets/images/bird.png

    #Municipio Calkini
    - lib/assets/images/festividadesCK/historiaCK.png
    - lib/assets/images/diaFestivoCK.jpg
    - lib/assets/images/festividadesCK/carnaval_principal.jpg
    - lib/assets/images/festividadesCK/carnaval1.jpg
    - lib/assets/images/festividadesCK/carnaval2.jpg
    - lib/assets/images/festividadesCK/carnaval3.jpg
    - lib/assets/images/festividadesCK/carnaval4.jpg
    - lib/assets/images/festividadesCK/carnaval5.jpg
    - lib/assets/images/festividadesCK/carnaval6.jpg
    - lib/assets/images/festividadesCK/sanisidro_principal.jpg
    - lib/assets/images/festividadesCK/sanisidro1.jpg
    - lib/assets/images/festividadesCK/sanisidro2.jpg
    - lib/assets/images/festividadesCK/sanisidro3.jpg
    - lib/assets/images/festividadesCK/fatima_principal.jpg
    - lib/assets/images/festividadesCK/fatima1.jpg
    - lib/assets/images/festividadesCK/fatima2.jpg
    - lib/assets/images/festividadesCK/fatima3.jpg
    - lib/assets/images/festividadesCK/fatima4.jpg
    - lib/assets/images/festividadesCK/fatima5.jpg
    - lib/assets/images/festividadesCK/fartesanal_principal.jpg
    - lib/assets/images/festividadesCK/fartesanal1.jpg
    - lib/assets/images/festividadesCK/fartesanal2.jpg
    - lib/assets/images/festividadesCK/fartesanal3.jpg
    - lib/assets/images/festividadesCK/fartesanal4.jpg
    - lib/assets/images/festividadesCK/fartesanal5.jpg

    #Hoteles
    - lib/assets/images/hoteles/hotelck/mayte_principal.jpg
    - lib/assets/images/hoteles/hotelck/mayte1.jpg
    - lib/assets/images/hoteles/hotelck/mayte2.jpg
    - lib/assets/images/hoteles/hotelck/mayte3.jpg
    - lib/assets/images/hoteles/hotelck/maya_principal.jpg
    - lib/assets/images/hoteles/hotelck/maya1.jpg
    - lib/assets/images/hoteles/hotelck/maya2.jpg
    - lib/assets/images/hoteles/hotelck/maya3.jpg
    - lib/assets/images/hoteles/hotelck/ceiba_principal.jpg
    - lib/assets/images/hoteles/hotelck/ceiba1.jpg
    - lib/assets/images/hoteles/hotelck/ceiba2.jpg
    - lib/assets/images/hoteles/hotelck/ceiba3.jpg
    - lib/assets/images/hoteles/hotelck/noemi_principal.jpg
    - lib/assets/images/hoteles/hotelck/noemi1.jpg
    - lib/assets/images/hoteles/hotelck/noemi2.jpg
    - lib/assets/images/hoteles/hotelck/noemi3.jpg
    - lib/assets/images/hoteles/hotelck/brenda_principal.jpg
    - lib/assets/images/hoteles/hotelck/brenda1.jpg
    - lib/assets/images/hoteles/hotelck/brenda2.jpg
    - lib/assets/images/hoteles/hotelck/brenda3.jpg

  #locales artesanales
    - lib/assets/images/locales/localesartck/chiich_principal.jpg
    - lib/assets/images/locales/localesartck/chiich1.jpg
    - lib/assets/images/locales/localesartck/chiich2.jpg
    - lib/assets/images/locales/localesartck/yc_principal.jpg
    - lib/assets/images/locales/localesartck/yc1.jpg
    - lib/assets/images/locales/localesartck/yc2.jpg
    - lib/assets/images/locales/localesartck/fidelia_principal.jpg
    - lib/assets/images/locales/localesartck/fidelia1.jpg
    - lib/assets/images/locales/localesartck/fidelia2.jpg
    - lib/assets/images/locales/localesartck/nicte_principal.png
    - lib/assets/images/locales/localesartck/nicte1.jpg
    - lib/assets/images/locales/localesartck/nicte2.jpg
    #restaurantes
    - lib/assets/images/locales/restaurantesck/palapa_principal.jpg
    - lib/assets/images/locales/restaurantesck/palapa1.jpg
    - lib/assets/images/locales/restaurantesck/palapa2.jpg
    - lib/assets/images/locales/restaurantesck/oasis_principal.jpg
    - lib/assets/images/locales/restaurantesck/oasis1.jpg
    - lib/assets/images/locales/restaurantesck/oasis2.jpg
    - lib/assets/images/locales/restaurantesck/superp_principal.jpg
    - lib/assets/images/locales/restaurantesck/superp1.jpg
    - lib/assets/images/locales/restaurantesck/superp2.jpg
    - lib/assets/images/locales/restaurantesck/bon_principal.jpg
    - lib/assets/images/locales/restaurantesck/bon1.jpg
    - lib/assets/images/locales/restaurantesck/bon2.jpg
    - lib/assets/images/locales/restaurantesck/isla_principal.jpg
    - lib/assets/images/locales/restaurantesck/isla1.jpg
    - lib/assets/images/locales/restaurantesck/isla2.jpg
    
    #LOCALES

    - lib/assets/images/locales/negociosck/ferre_principal.jpg
    - lib/assets/images/locales/negociosck/ferre1.jpg
    - lib/assets/images/locales/negociosck/coppel_principal.jpg
    - lib/assets/images/locales/negociosck/coppel1.jpg
    - lib/assets/images/locales/negociosck/jugueteria_principal.jpg
    - lib/assets/images/locales/negociosck/jugueteria1.jpg

    #BALNEARIOS
    - lib/assets/images/locales/balneariosck/balneario_principal.jpg
    - lib/assets/images/locales/balneariosck/balneario1.jpg
    - lib/assets/images/locales/balneariosck/balneario2.jpg
    - lib/assets/images/locales/balneariosck/balneario3.jpg
    - lib/assets/images/locales/balneariosck/chuc_principal.jpg
    - lib/assets/images/locales/balneariosck/chuc1.jpg
    - lib/assets/images/locales/balneariosck/chuc2.jpg
    - lib/assets/images/locales/balneariosck/chuc3.jpg
    - lib/assets/images/locales/balneariosck/quinta_principal.jpg
    - lib/assets/images/locales/balneariosck/chuc1.jpg
    - lib/assets/images/locales/balneariosck/chuc_principal.jpg
    - lib/assets/images/locales/balneariosck/chuc2.jpg
    - lib/assets/images/locales/balneariosck/chuc3.jpg

    #CENTROS RELIGIOSOS
    - lib/assets/images/locales/religiososck/sanluis_principales.jpg
    - lib/assets/images/locales/religiososck/sanluis1.jpg
    - lib/assets/images/locales/religiososck/sanluis2.jpg
    - lib/assets/images/locales/religiososck/sanluis3.jpeg
    - lib/assets/images/locales/religiososck/iglesia_principal.jpg
    - lib/assets/images/locales/religiososck/iglesia1.jpg
    - lib/assets/images/locales/religiososck/iglesia2.jpg
    - lib/assets/images/locales/religiososck/iglesia3.jpg
    - lib/assets/images/locales/religiososck/fatima_principal.jpg
    - lib/assets/images/locales/religiososck/fatima1.jpg
    - lib/assets/images/locales/religiososck/fatima2.jpg
    - lib/assets/images/locales/religiososck/fatima3.jpg

    #CAFETERIAS
    - lib/assets/images/locales/restaurantesck/daju_principal.jpg
    - lib/assets/images/locales/restaurantesck/daju1.jpg
    - lib/assets/images/locales/restaurantesck/daju2.jpg
    - lib/assets/images/locales/restaurantesck/daju3.jpg

    #Transporte
    - lib/assets/images/locales/transporteck/ado_principal.jpg
    - lib/assets/images/locales/transporteck/ado1.jpg
    - lib/assets/images/locales/transporteck/ado2.jpg
    - lib/assets/images/locales/transporteck/untrac_principal.jpg


    #BECAL
    - lib/assets/images/festividadesBC/
    

    #DZITBALCHE
    - lib/assets/images/festividadesDZ/


    
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
